In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import tensorflow 
import streamlit as st

2026-10-25 18:42:41.588595: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

## DATA GATHERING

In [43]:
data=pd.read_csv('huge_1M_titanic.csv')

In [44]:
data=data.sample(20000)

## DATA PREPROCESING

In [45]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
78177,79487,0,3,"Name79487, Mrs. Surname79487",female,42.0,0,5,29106,21.100324,NaN,S
87594,88904,0,2,"Name88904, Mr. Surname88904",male,20.0,0,0,3474,1.799274,NaN,S
436008,437318,0,3,"Name437318, Mr. Surname437318",male,30.0,0,0,C.A. 6212,16.095665,NaN,S
954833,956143,0,3,"Name956143, Mrs. Surname956143",female,21.0,4,2,330958,21.833732,NaN,NaN
493798,495108,1,2,"Name495108, Mr. Surname495108",male,13.0,1,1,113056,28.281826,NaN,S

In [46]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,2.000000e+04,20000.000000,20000.000000,16147.000000,20000.000000,20000.000000,20000.000000
mean,4.990845e+05,0.382900,2.310050,29.174707,0.492600,0.360250,33.324452
std,2.886776e+05,0.486106,0.834778,12.744369,1.060284,0.758089,47.713556
min,1.487000e+03,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2.516802e+05,0.000000,2.000000,21.000000,0.000000,0.000000,8.556520
50%,4.964625e+05,0.000000,3.000000,29.000000,0.000000,0.000000,15.822233
75%,7.492548e+05,1.000000,3.000000,37.000000,1.000000,0.000000,35.252372
max,1.001271e+06,1.000000,3.000000,87.000000,8.000000,6.000000,547.447637

In [47]:
data.info()

<class 'pandas.DataFrame'>
Index: 20000 entries, 78177 to 879873
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  20000 non-null  int64
 1   Survived     20000 non-null  int64
 2   Pclass       20000 non-null  int64
 3   Name         20000 non-null  str
 4   Sex          20000 non-null  str
 5   Age          16147 non-null  float64
 6   SibSp        20000 non-null  int64
 7   Parch        20000 non-null  int64
 8   Ticket       20000 non-null  str
 9   Fare         20000 non-null  float64
 10  Cabin        4592 non-null   str
 11  Embarked     19957 non-null  str
dtypes: float64(2), int64(5), str(5)
memory usage: 2.8 MB

In [48]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [49]:
data['Embarked'].dropna(inplace=True)

In [50]:
data=data[['Survived','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]

In [51]:
data.info()

<class 'pandas.DataFrame'>
Index: 20000 entries, 78177 to 879873
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  20000 non-null  int64
 1   Pclass    20000 non-null  int64
 2   Sex       20000 non-null  str
 3   Age       16147 non-null  float64
 4   SibSp     20000 non-null  int64
 5   Parch     20000 non-null  int64
 6   Fare      20000 non-null  float64
 7   Embarked  19957 non-null  str
dtypes: float64(2), int64(4), str(2)
memory usage: 1.5 MB

In [52]:
data.isnull().sum()

Survived       0
Pclass         0
Sex            0
Age         3853
SibSp          0
Parch          0
Fare           0
Embarked      43
dtype: int64

In [53]:
data.head()

        Survived  Pclass     Sex   Age  SibSp  Parch       Fare Embarked
78177          0       3  female  42.0      0      5  21.100324        S
87594          0       2    male  20.0      0      0   1.799274        S
436008         0       3    male  30.0      0      0  16.095665        S
954833         0       3  female  21.0      4      2  21.833732      NaN
493798         1       2    male  13.0      1      1  28.281826        S

In [54]:
data['Age']=data['Age'].fillna(data['Age'].mean(),inplace=True)

/var/folders/86/zjyjby2d7d5bxr35vg_p5myw0000gn/T/ipykernel_65406/2347312885.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['Age']=data['Age'].fillna(data['Age'].mean(),inplace=True)

In [55]:
data['Embarked']=data['Embarked'].fillna(data['Embarked'].mode()[0],inplace=True)

/var/folders/86/zjyjby2d7d5bxr35vg_p5myw0000gn/T/ipykernel_65406/1873395046.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['Embarked']=data['Embarked'].fillna(data['Embarked'].mode()[0],inplace=True)

In [56]:
data.head(10)

        Survived  Pclass     Sex        Age  SibSp  Parch       Fare Embarked
78177          0       3  female  42.000000      0      5  21.100324        S
87594          0       2    male  20.000000      0      0   1.799274        S
436008         0       3    male  30.000000      0      0  16.095665        S
954833         0       3  female  21.000000      4      2  21.833732        S
493798         1       2    male  13.000000      1      1  28.281826        S
532382         1       1  female  29.174707      1      1  53.969119        S
956657         0       3    male  22.000000      0      0  10.425134        S
584872         1       3    male  25.000000      1      0   0.000000        S
13710          0       2    male  43.000000      1      0  48.357999        C
116204         0       2    male  33.000000      1      0  43.719346        C

In [57]:
data.info()

<class 'pandas.DataFrame'>
Index: 20000 entries, 78177 to 879873
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  20000 non-null  int64
 1   Pclass    20000 non-null  int64
 2   Sex       20000 non-null  str
 3   Age       20000 non-null  float64
 4   SibSp     20000 non-null  int64
 5   Parch     20000 non-null  int64
 6   Fare      20000 non-null  float64
 7   Embarked  20000 non-null  str
dtypes: float64(2), int64(4), str(2)
memory usage: 1.5 MB

In [58]:
data['Age']=data['Age'].astype('int32')
data['Survived']=data['Survived'].astype('int32')
data['Pclass']=data['Pclass'].astype('int32')
data['SibSp']=data['SibSp'].astype('int32')
data['Parch']=data['Parch'].astype('int32')

In [59]:
data.info()

<class 'pandas.DataFrame'>
Index: 20000 entries, 78177 to 879873
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  20000 non-null  int32
 1   Pclass    20000 non-null  int32
 2   Sex       20000 non-null  str
 3   Age       20000 non-null  int32
 4   SibSp     20000 non-null  int32
 5   Parch     20000 non-null  int32
 6   Fare      20000 non-null  float64
 7   Embarked  20000 non-null  str
dtypes: float64(1), int32(5), str(2)
memory usage: 1.1 MB

## DATA CLEANING

In [60]:
data['Embarked']=data['Embarked'].replace({'S':'Southampton','C':'Cherbourg','Q':'Queenstown'})

In [61]:
data.head(10)

        Survived  Pclass     Sex  Age  SibSp  Parch       Fare     Embarked
78177          0       3  female   42      0      5  21.100324  Southampton
87594          0       2    male   20      0      0   1.799274  Southampton
436008         0       3    male   30      0      0  16.095665  Southampton
954833         0       3  female   21      4      2  21.833732  Southampton
493798         1       2    male   13      1      1  28.281826  Southampton
532382         1       1  female   29      1      1  53.969119  Southampton
956657         0       3    male   22      0      0  10.425134  Southampton
584872         1       3    male   25      1      0   0.000000  Southampton
13710          0       2    male   43      1      0  48.357999    Cherbourg
116204         0       2    male   33      1      0  43.719346    Cherbourg

In [62]:
data.shape

(20000, 8)

In [63]:
data['Fare']=data['Fare'].astype('int32')

In [64]:
data.head()

        Survived  Pclass     Sex  Age  SibSp  Parch  Fare     Embarked
78177          0       3  female   42      0      5    21  Southampton
87594          0       2    male   20      0      0     1  Southampton
436008         0       3    male   30      0      0    16  Southampton
954833         0       3  female   21      4      2    21  Southampton
493798         1       2    male   13      1      1    28  Southampton

In [65]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [66]:
label=LabelEncoder()

In [67]:
data['Sex']=label.fit_transform(data['Sex'])

In [68]:
data.head()

        Survived  Pclass  Sex  Age  SibSp  Parch  Fare     Embarked
78177          0       3    0   42      0      5    21  Southampton
87594          0       2    1   20      0      0     1  Southampton
436008         0       3    1   30      0      0    16  Southampton
954833         0       3    0   21      4      2    21  Southampton
493798         1       2    1   13      1      1    28  Southampton

In [69]:
ohe=OneHotEncoder(sparse_output=False)

In [70]:
Embarked=ohe.fit_transform(data[['Embarked']])

In [71]:
Embarked=pd.DataFrame(Embarked,columns=['Embarked_C','Embarked_Q','Embarked_S'],index=data.index)

In [72]:
Embarked.head()

        Embarked_C  Embarked_Q  Embarked_S
78177          0.0         0.0         1.0
87594          0.0         0.0         1.0
436008         0.0         0.0         1.0
954833         0.0         0.0         1.0
493798         0.0         0.0         1.0

In [73]:
data=pd.concat([data,Embarked],axis=1)

In [74]:
data.drop(columns=['Embarked'],inplace=True)

In [75]:
data.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
78177,0,3,0,42,0,5,21,0.0,0.0,1.0
87594,0,2,1,20,0,0,1,0.0,0.0,1.0
436008,0,3,1,30,0,0,16,0.0,0.0,1.0
954833,0,3,0,21,4,2,21,0.0,0.0,1.0
493798,1,2,1,13,1,1,28,0.0,0.0,1.0

In [76]:
from sklearn.preprocessing import StandardScaler

In [77]:
scale=StandardScaler()

In [78]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='str')

In [79]:
num_cols=['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [80]:
data[num_cols]=scale.fit_transform(data[num_cols])

In [81]:
data.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
78177,0,0.826528,0,1.122954,-0.464604,6.120478,-0.248616,0.0,0.0,1.0
87594,0,-0.371426,1,-0.798275,-0.464604,-0.475220,-0.667986,0.0,0.0,1.0
436008,0,0.826528,1,0.075011,-0.464604,-0.475220,-0.353459,0.0,0.0,1.0
954833,0,0.826528,0,-0.710946,3.308065,2.163059,-0.248616,0.0,0.0,1.0
493798,1,-0.371426,1,-1.409575,0.478563,0.843920,-0.101837,0.0,0.0,1.0

In [82]:
data.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [83]:
import pickle

In [84]:
with open('label.pkl','wb') as file:
    pickle.dump(label,file)

In [85]:
with open('ohe.pkl','wb') as file:
    pickle.dump(ohe,file)

In [86]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scale,file)

## TRAIN TEST SPLIT

In [87]:
X=data.drop(columns=['Survived'])

In [88]:
X.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
78177,0.826528,0,1.122954,-0.464604,6.120478,-0.248616,0.0,0.0,1.0
87594,-0.371426,1,-0.798275,-0.464604,-0.475220,-0.667986,0.0,0.0,1.0
436008,0.826528,1,0.075011,-0.464604,-0.475220,-0.353459,0.0,0.0,1.0
954833,0.826528,0,-0.710946,3.308065,2.163059,-0.248616,0.0,0.0,1.0
493798,-0.371426,1,-1.409575,0.478563,0.843920,-0.101837,0.0,0.0,1.0

In [90]:
X.isnull().sum()

Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [89]:
Y=data['Survived']

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [93]:
x_train,x_valid,y_train,y_valid=train_test_split(x_train,y_train,test_size=0.2,random_state=42)

In [94]:
x_train.shape

(12800, 9)

## MODEL BUILDING

In [95]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [96]:
model=Sequential([Dense(128,input_shape=(x_train.shape[1],),activation='relu'),#first hidden layer
            Dense(64,activation='relu'),
           Dense(32,activation='relu'),
           Dense(1,activation='sigmoid')] #output layer
           )

/Users/aseem/Desktop/Tutedude_GENAI/Deep Learning/venv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [97]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,649 (45.50 KB)

 Trainable params: 11,649 (45.50 KB)

 Non-trainable params: 0 (0.00 B)

In [98]:
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [99]:
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [100]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,649 (45.50 KB)

 Trainable params: 11,649 (45.50 KB)

 Non-trainable params: 0 (0.00 B)

In [101]:
EarlyStopping=EarlyStopping(monitor='val_loss',patience=7,restore_best_weights=True)

In [102]:
model.fit(x_train,y_train,validation_data=(x_valid,y_valid),epochs=15,batch_size=3,callbacks=[EarlyStopping])

Epoch 1/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.8210 - loss: 0.4266 - val_accuracy: 0.8344 - val_loss: 0.3823
Epoch 2/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8442 - loss: 0.3873 - val_accuracy: 0.8475 - val_loss: 0.3746
Epoch 3/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8479 - loss: 0.3730 - val_accuracy: 0.8375 - val_loss: 0.4133
Epoch 4/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8504 - loss: 0.3665 - val_accuracy: 0.8438 - val_loss: 0.3756
Epoch 5/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8478 - loss: 0.3636 - val_accuracy: 0.8459 - val_loss: 0.3838
Epoch 6/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8523 - loss: 0.3594 - val_accuracy: 0.8444 - val_loss: 0.3728
Epoch 7/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.8555 - loss: 0.3568 - val_accuracy: 0.8528 - val_loss: 0.3554
Epoch 8/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.8557 - loss: 0.3482 - val_accuracy: 0.8547 - val_loss: 0.3498
Epoch 9/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.8544 - loss: 0.3571 - val_accuracy: 0.8434 - val_loss: 0.3504
Epoch 10/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.8541 - loss: 0.3495 - val_accuracy: 0.8522 - val_loss: 0.3508
Epoch 11/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.8544 - loss: 0.3464 - val_accuracy: 0.8509 - val_loss: 0.3526
Epoch 12/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.8552 - loss: 0.3552 - val_accuracy: 0.8459 - val_loss: 0.3643
Epoch 13/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.8560 - loss: 0.3484 - val_accuracy: 0.8559 - val_loss: 0.3469
Epoch 14/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.8529 - loss: 0.3474 - val_accuracy: 0.8413 - val_loss: 0.3641
Epoch 15/15
4267/4267 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.8524 - loss: 0.3442 - val_accuracy: 0.8450 - val_loss: 0.3519

In [103]:
model.save('titanic_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.