In [1]:
from tensorflow.keras.models import load_model
import pandas as pd
import pickle
import tensorflow as tf

2026-10-25 19:01:24.209822: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [22]:
with open('scaler.pkl','rb') as f:
    scaler=pickle.load(f)

with open('label.pkl','rb') as f:
    label=pickle.load(f)

with open('ohe.pkl','rb') as f:
    ohe=pickle.load(f)

In [3]:
model=load_model('titanic_model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [149]:
user={
    'Pclass':2,
    'Sex':'female',
    'Age':59,
    'SibSp':0,
    'Parch':0,
    'Fare':32,
    'Embarked':'Cherbourg'
}

In [150]:
user=pd.DataFrame([user])

In [151]:
user

   Pclass     Sex  Age  SibSp  Parch  Fare   Embarked
0       2  female   59      0      0    32  Cherbourg

In [152]:
new=ohe.transform(user[['Embarked']])

In [153]:
new=pd.DataFrame(new,columns=['Embarked_C','Embarked_Q','Embarked_S'])

In [154]:
user=pd.concat([user,new],axis=1)

In [155]:
user.drop(['Embarked'],axis=1,inplace=True)

In [156]:
user

   Pclass     Sex  Age  SibSp  Parch  Fare  Embarked_C  Embarked_Q  Embarked_S
0       2  female   59      0      0    32         1.0         0.0         0.0

In [157]:
user['Sex']=label.transform(user['Sex'])

In [158]:
user

   Pclass  Sex  Age  SibSp  Parch  Fare  Embarked_C  Embarked_Q  Embarked_S
0       2    0   59      0      0    32         1.0         0.0         0.0

In [159]:
user.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_C',
       'Embarked_Q', 'Embarked_S'],
      dtype='str')

In [160]:
cols=['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [161]:
user[cols] = scaler.transform(user[cols])

In [162]:
user

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,-0.371426,0,2.607539,-0.464604,-0.47522,-0.017963,1.0,0.0,0.0

In [163]:
y=model.predict(user)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

In [164]:
y

array([[0.80592525]], dtype=float32)

In [165]:
if y[0][0]>0.5:
    print ('There may be a chance of survival')
else:
    print('God May bless you')

There may be a chance of survival